name: CI
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: RSpec on Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.0
          - 2.7
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: RSpec
        run: bundle exec rspec

  style:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2
          ruby-version: 3.0
          bundler-cache: true

      - name: RuboCop
        run: bundle exec rubocop
